### PR TITLE
Setup Image Building

### PR DESCRIPTION
**Pull request by salvis2**
Set up image configuration and building for https://github.com/icesat2py/icepyx-gallery/issues/1

@JessicaS11 here are the things I think need doing before trying this out:
- [x] Enter github secret `DOCKER_USERNAME` for this repo
- [x] Enter github secret `DOCKER_PASSWORD` for this repo
- [x] Decide on image name and DockerHub location for `build-and-push-icepyx-image.yaml`
- [x] Review package list in `environment.yml` and `requirements.txt`

### CODE REVIEW

**Comment by JessicaS11** [comment]
I tried creating an icepyx organization, then realized what I needed was a login, but it hasn't yet freed up the icepyx username (even since the organization is deleted). I'm going to wait and see if it will work later today or tomorrow, otherwise I'll set something up with different names.

Will it work for me to just [directly link icesat2py on GitHub and icepyx on Docker](https://github.com/fabric8io/jenkinshift/blob/master/vendor/github.com/docker/docker/docs/docker-hub/builds.md)? Then I don't think we need to store the authentication info.

**Comment by salvis2** [comment]
> I tried creating an icepyx organization, then realized what I needed was a login

Right, at the end of the day all we need is a username and a password. You could use your own login as an approved maintainer of a DockerHub Icepyx organization, similar to how we had permission to push to [uwhackweeks](https://hub.docker.com/u/uwhackweeks) for the IceSat-2 Hackweek. You can also just make a standalone user and push to their images.

> Will it work for me to just directly link icesat2py on GitHub and icepyx on Docker?

I am unsure. My two concerns are that I have not tried this before and I don't know how well the `repo2docker` functionality is setup in this workflow. I'm inclined to think that we need to use the current `repo2docker` GitHub Action because it's set up to track certain files that normal Docker builds might gloss over. That repo is also archived and the `builds.md` file has a lot of broken links, so I'm suspicious about it working without a lot of fiddling.

**Comment by JessicaS11** [comment]
I created an icepyx account on Docker, so this repo now has a DOCKER_USERNAME and DOCKER_PASSWORD set. Do we also need to set up an organization on Docker so that there can be shared management of the image? Or can you just share what you set up?

**Comment by salvis2** [comment]
If you want shared management of the image, I think you need an
organization. The way I tested leaves it under my own Docker username:
`sebialvis/icepyx-test-image`. I doubt anyone else can push images there.

**Comment by salvis2** [comment]
For clarity, I put a comment here: https://github.com/icesat2py/icepyx-gallery/issues/1#issuecomment-712553301

>Per a suggestion by @scottyhq , I put in my own credentials and a place for an image to live under my username, and the build worked! https://github.com/salvis2/icepyx-examples-image/actions/runs/316625746

>@JessicaS11 if you have credentials to put into the icepyx-gallery repo tomorrow, I'll use them to build the image and get to testing the gallery. I can test with my own image otherwise and we will just switch things later.

**Pull request merged**
